services:

  backend:
    build:
      context: .
      dockerfile: backend_docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend_docker/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend